.\" Copyright 2003 Red Hat, Inc.
.\" Written by Nalin Dahyabhai <nalin@redhat.com>
.TH pam_rps 8 2003/6/30 "Red Hat Linux" "System Administrator's Manual"

.SH NAME
pam_rps \- challenge-response authentication

.SH SYNOPSIS
.B auth sufficient pam_rps.so

.SH DESCRIPTION
pam_rps.so is designed to provide a true challenge-response authentication
mechanism for PAM-enabled applications.

Without pam_rps, successful authentication can only occur for a user if the
user has previously established an authentication token for use with the
server.  Using pam_rps removes this limitation.

.SH ARGUMENTS
.IP debug
Enable module debugging.  The module will log its progress to syslog.
.IP throw=\fInumber\fP
The challenge issued to the user is derived from a random number.  This
argument allows the administrator to control which challenge will be presented
to the user.  This argument is meant for use only when debugging.

.SH NOTES
Never use this module.

.SH BUGS
Let's hope not, but if you find any, please report them via the "Bug Track"
link at http://bugzilla.redhat.com/bugzilla/

.SH AUTHOR
Nalin Dahyabhai <nalin@redhat.com>
