.TH pam_loginuid 8 2005/07/29 "Red Hat Linux" "System Administrator's Manual"
.SH NAME
pam_loginuid \- record user's login uid to the process attribute
.SH SYNOPSIS
.B session required /lib/security/pam_loginuid.so
.br

.SH DESCRIPTION
pam_loginuid sets the loginuid process attribute for the process that was authenticated. This is necessary for applications to be correctly audited. This pam module should only be used for entry point applications like: login, sshd, gdm, vsftpd, crond, at, and remote. There are probably other entry point applications besides these. You should not use it for applications like sudo or su as that defeats the purpose by changing the loginuid to the account they just switched to.

.SH ARGUMENTS
.IP require_auditd
This option, when given, will cause this module to query the audit daemon status and deny logins if it is not running.

.SH EXAMPLE
\fB/etc/pam.d/gdm\fP:
.br
auth       required     pam_stack.so service=system-auth
.br
auth       required     pam_nologin.so
.br
account    required     pam_stack.so service=system-auth
.br
password   required     pam_stack.so service=system-auth
.br
session    required     pam_stack.so service=system-auth
.br
session    required     pam_loginuid.so
.br
session    optional     pam_console.so
.br

.SH SEE ALSO
auditd(8), auditctl(8)

.SH BUGS
Let's hope not, but if you find any, please email the author.  

.SH AUTHOR
Steve Grubb <sgrubb@redhat.com>
