# $Id$
#
# This Makefile controls a build process of $(TITLE) module for
# Linux-PAM. You should not modify this Makefile (unless you know
# what you are doing!).
#
#

include ../../Make.Rules

TITLE=pam_localuser

include ../Simple.Rules
