.\" Copyright 2001 Red Hat, Inc.
.TH pam_console_appy 8 2001/3/6 "Red Hat" "System Administrator's Manual"
.SH NAME
pam_console_apply \- set or revoke permissions for users at the system console
.SH SYNOPSIS
.B pam_console_apply [-r]
.SH DESCRIPTION
\fBpam_console_apply\fP sets or resets permissions on devices in the same
manner as pam_console.
.br
If \fI/var/lock/console.lock\fP exists, \fBpam_console_apply\fP will grant
permissions to the user listed therein.  If the lock file does not exist,
permissions are reset to those listed in \fI/etc/security/console.perms\fP,
which should be configured to set permissions on devices so that \fBroot\fP
owns them.
.SH ARGUMENTS
.IP -r
Signals \fBpam_console_apply\fP to reset permissions.  The default is to set
permissions so that the user listed in \fI/var/lock/console.lock\fP has access
to the devices, and to reset permissions if no such file exists.
.SH FILES
\fI/var/lock/console.lock\fP
.br
\fI/etc/security/console.perms\fP
.SH "SEE ALSO"
.BR pam_console(8)
.br
.BR console.perms(5)
.br
.SH BUGS
Let's hope not, but if you find any, please report them via the "Bug Track"
link at http://developer.redhat.com/
.SH AUTHOR
Nalin Dahyabhai <nalin@redhat.com>, using code shamelessly stolen from parts of
pam_console.
